# Screen
SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 600
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)
# Screen points
SCREEN_BOTTOM_LEFT = (0, 0)
SCREEN_BOTTOM_RIGHT = (SCREEN_WIDTH, 0)
SCREEN_TOP_LEFT = (0, SCREEN_HEIGHT)
SCREEN_TOP_RIGHT = (SCREEN_WIDTH, SCREEN_HEIGHT)
SCREEN_CENTER = (SCREEN_WIDTH / 2, SCREEN_HEIGHT / 2)

# Gameplay
MIN_DAMAGE = 2

BULLET_RADIUS = 1
BULLET_MASS = 2
BULLET_STRENGTH = 500

CANNON_POWER = 1000

# Bomber
BOMBER_WIDTH = 20
BOMBER_HEIGHT = 30

BOMBER_STRENGTH = 1000

BOMBER_TORQUE = 30000
BOMBER_MAIN_ENGINE_THRUST = 10000
BOMBER_BRAKE_FORCE = 15000
BOMBER_REVERSE_ENGINE_THRUST = 8000
BOMBER_ANG_VEL_LIMIT = 10

# Asteroids
ASTEROID_VEL_LIMIT = 100
ASTEROID_BASE_STRENGTH = 200
ASTEROID_BASE_MASS = 50

# Collision types
CT_BOMBER = 0
CT_ASTEROID = 1
CT_BULLET = 2
